CREATE TABLE [dbo].[PROVEEDOR]
(
[RUCPRO] [char] (11) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PROVEEDOR] ADD CONSTRAINT [PROVEEDOR_pk] PRIMARY KEY CLUSTERED ([RUCPRO]) ON [PRIMARY]
GO
