CREATE TABLE [dbo].[COMPRA]
(
[CODCOM] [char] (5) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NOMINS] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FECVEN] [date] NOT NULL,
[IDEMP] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPRA] ADD CONSTRAINT [COMPRA_pk] PRIMARY KEY CLUSTERED ([CODCOM]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPRA] ADD CONSTRAINT [COMPRA_EMPLEADO] FOREIGN KEY ([IDEMP]) REFERENCES [dbo].[EMPLEADO] ([IDEMP])
GO
