CREATE TABLE [dbo].[EMPLEADO]
(
[IDEMP] [int] NOT NULL,
[NOMEMP] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APPAT] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APMAT] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CELEMP] [char] (9) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TUREMP] [char] (1) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLEADO] ADD CONSTRAINT [EMPLEADO_pk] PRIMARY KEY CLUSTERED ([IDEMP]) ON [PRIMARY]
GO
