CREATE TABLE [dbo].[CLIENTE]
(
[IDCLI] [int] NOT NULL,
[NOMCLI] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APPAT] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[APMAT] [varchar] (10) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CELCLI] [char] (9) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[CLIENTE] ADD CONSTRAINT [CLIENTE_pk] PRIMARY KEY CLUSTERED ([IDCLI]) ON [PRIMARY]
GO
