CREATE TABLE [dbo].[VENTA]
(
[CODVEN] [char] (5) COLLATE Modern_Spanish_CI_AS NOT NULL,
[FECVEN] [date] NOT NULL,
[IDEMP] [int] NOT NULL,
[IDCLI] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_pk] PRIMARY KEY CLUSTERED ([CODVEN]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_CLIENTE] FOREIGN KEY ([IDCLI]) REFERENCES [dbo].[CLIENTE] ([IDCLI])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_EMPLEADO] FOREIGN KEY ([IDEMP]) REFERENCES [dbo].[EMPLEADO] ([IDEMP])
GO
