CREATE TABLE [dbo].[MENU]
(
[IDMEN] [int] NOT NULL,
[TIPMEN] [varchar] (20) COLLATE Modern_Spanish_CI_AS NOT NULL,
[PREMEN] [decimal] (8, 2) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[MENU] ADD CONSTRAINT [MENU_pk] PRIMARY KEY CLUSTERED ([IDMEN]) ON [PRIMARY]
GO
